### PR TITLE
GS-54: Prospect support

### PR DESCRIPTION
**Pull request by coldrunKacper**
- Implementing Prospect extension's support (if the extension is installed and enabled).
- Adding Prospect data into caching.

Sample Prospect report view:
gs-54-prospect

Prospect report fields are susceptible to word replacement (during cache building).
gs-54-word-replacement-list

gs-54-prospect-word-replaced

### CODE REVIEW

**Comment by guanhuan** [comment]
@coldrunKacper does word replacement "Case" -> "Prospect" impact the axis labels as well? Could you make a screenshot with Prospect as the labels instead of cases here and explain how it's done?

**Comment by guanhuan** [comment]
Also is the order of the axes in the pool always alphabetic or is it something we can decide?

**Comment by coldrunKacper** [comment]
1. Yes, the fields are now word replacement sensitive (I've updated PR description with screenshots).
2. The alphabetical order is set by us (we can change it).

**Comment by guanhuan** [comment]
Cool @coldrunKacper . Just to confirm:
1. in the screenshot it says "(word replaced)". Is that just an annotation? When we replace case -> prospect on the site, that won't show up if I am correct.
2. Thanks, good to know it can be modified. Let's keep it as it is for now.

**Comment by coldrunKacper** [comment]
Yes, it's added by me to show the modified labels on Prospect report screen (just for screenshot purpose).

**Comment by jamienovick** [comment]
Just to confirm - does this include all case and contribution custom fields? @coldrunKacper  @guanhuan ?

**Pull request merged**
